// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: car_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Car struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand        string  `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model        string  `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year         int32   `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Displacement float32 `protobuf:"fixed32,6,opt,name=displacement,proto3" json:"displacement,omitempty"`
	Body         string  `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	Mpg          float32 `protobuf:"fixed32,8,opt,name=mpg,proto3" json:"mpg,omitempty"`
	Cylinders    int32   `protobuf:"varint,9,opt,name=cylinders,proto3" json:"cylinders,omitempty"`
	Horsepower   float32 `protobuf:"fixed32,10,opt,name=horsepower,proto3" json:"horsepower,omitempty"`
	BrakeSystem  string  `protobuf:"bytes,11,opt,name=brake_system,json=brakeSystem,proto3" json:"brake_system,omitempty"`
	Aspiration   string  `protobuf:"bytes,12,opt,name=aspiration,proto3" json:"aspiration,omitempty"`
	Acceleration float32 `protobuf:"fixed32,13,opt,name=acceleration,proto3" json:"acceleration,omitempty"`
	Country      string  `protobuf:"bytes,14,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *Car) Reset() {
	*x = Car{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_car_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_car_message_proto_rawDescGZIP(), []int{0}
}

func (x *Car) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Car) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Car) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Car) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Car) GetDisplacement() float32 {
	if x != nil {
		return x.Displacement
	}
	return 0
}

func (x *Car) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Car) GetMpg() float32 {
	if x != nil {
		return x.Mpg
	}
	return 0
}

func (x *Car) GetCylinders() int32 {
	if x != nil {
		return x.Cylinders
	}
	return 0
}

func (x *Car) GetHorsepower() float32 {
	if x != nil {
		return x.Horsepower
	}
	return 0
}

func (x *Car) GetBrakeSystem() string {
	if x != nil {
		return x.BrakeSystem
	}
	return ""
}

func (x *Car) GetAspiration() string {
	if x != nil {
		return x.Aspiration
	}
	return ""
}

func (x *Car) GetAcceleration() float32 {
	if x != nil {
		return x.Acceleration
	}
	return 0
}

func (x *Car) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_car_message_proto protoreflect.FileDescriptor

var file_car_message_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xde, 0x02, 0x0a, 0x03, 0x43, 0x61, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x79,
	0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12,
	0x22, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x70, 0x67, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x70, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x79, 0x6c,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x79,
	0x6c, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x6f, 0x72, 0x73, 0x65,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x68, 0x6f, 0x72,
	0x73, 0x65, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x72, 0x61, 0x6b, 0x65,
	0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62,
	0x72, 0x61, 0x6b, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x73,
	0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x73, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63,
	0x63, 0x65, 0x6c, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x6c, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x72, 0x6b, 0x68, 0x61, 0x74, 0x2f, 0x4b,
	0x69, 0x6e, 0x6f, 0x43, 0x61, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_car_message_proto_rawDescOnce sync.Once
	file_car_message_proto_rawDescData = file_car_message_proto_rawDesc
)

func file_car_message_proto_rawDescGZIP() []byte {
	file_car_message_proto_rawDescOnce.Do(func() {
		file_car_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_car_message_proto_rawDescData)
	})
	return file_car_message_proto_rawDescData
}

var file_car_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_car_message_proto_goTypes = []interface{}{
	(*Car)(nil), // 0: pb.Car
}
var file_car_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_car_message_proto_init() }
func file_car_message_proto_init() {
	if File_car_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_car_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Car); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_car_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_car_message_proto_goTypes,
		DependencyIndexes: file_car_message_proto_depIdxs,
		MessageInfos:      file_car_message_proto_msgTypes,
	}.Build()
	File_car_message_proto = out.File
	file_car_message_proto_rawDesc = nil
	file_car_message_proto_goTypes = nil
	file_car_message_proto_depIdxs = nil
}
